### ISSUE TITLE
match stats not recorded

### ISSUE THREAD

**Issue by frankthetank001** [frankthetank001/HoNfigurator#2]
Currently suspected issue in the config file, which means that the match stats are not recorded after every game. Should be an easy fix to compare working config files to the one being used by honfigurator

**Comment by iDunoPlay** [comment]
![issue](https://user-images.githubusercontent.com/102306952/182091936-837a6e05-091c-4dd6-8432-7982f3c2d4a3.png)
Potential rootcause. Delay the bot to restart the server after some delay (30seconds later).

**Comment by frankthetank001** [comment]
resolved this
issue was from storing hon configuration files in the same folder as the hon install directory.
Moved to seperate location {hon_directory}..\ and resolved issue
